theme: jekyll-theme-minimal
title: Exosuit Slope Detection
description: Detecting walking and running slopes using IMUS
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
